name: check_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=1.5.2
  - pip=20.3.3
  - pytest=7.1.3
  - scipy=1.6.1
  - pip:
      - wandb==0.13.9
      - setuptools==66.1.1
      - protobuf==3.19.0
      - omegaconf==2.2
      - mlflow==2.1.1